import { Module } from './types';

export const CURRICULUM: Module[] = [
  {
    id: 'mod-imagen',
    title: '1. Diagnóstico por Imágenes (Dr. Cotrina)',
    lessons: [
      {
        id: 'img-maestria',
        title: 'Maestría Radiográfica',
        description: 'Las 10 claves del éxito diagnóstico por imagen.',
        icon: '📸',
        color: 'bg-indigo-700',
        questions: [
          { id: 'rad1', text: 'Según la Regla de Isometría de Cieszynski (Bisectriz), el rayo central debe incidir perpendicularmente a:', options: ['El eje largo del diente', 'El plano de la película', 'La bisectriz del ángulo formado por el diente y la película', 'El plano oclusal'], correctAnswerIndex: 2, explanation: 'El rayo debe ser perpendicular a la bisectriz del ángulo entre diente y película.', type: 'multiple-choice' },
          { id: 'rad2', text: '¿Cuál es la causa principal del Escorzamiento (Foreshortening) en una radiografía?', options: ['Insuficiente angulación vertical', 'Excesiva angulación vertical', 'Angulación horizontal incorrecta', 'Película mal centrada'], correctAnswerIndex: 1, explanation: 'Una excesiva angulación vertical acorta (escorza) la imagen proyectada.', type: 'multiple-choice' },
          { id: 'rad3', text: '¿Qué error de técnica produce la "Elongación" de la imagen radiográfica?', options: ['Excesiva angulación vertical', 'Insuficiente angulación vertical', 'Falta de paralelismo', 'Movimiento del paciente'], correctAnswerIndex: 1, explanation: 'La insuficiente angulación vertical estira (elonga) la imagen proyectada.', type: 'multiple-choice' },
          { id: 'rad4', text: 'En la técnica de Clark (Regla MLOV), si un objeto se mueve en la MISMA dirección que el desplazamiento del cono, este se ubica por:', options: ['Vestibular / Bucal', 'Lingual / Palatino', 'Mesial', 'Distal'], correctAnswerIndex: 1, explanation: 'Mismo Lingual, Opuesto Vestibular. Indica posición lingual/palatina.', type: 'multiple-choice' },
          { id: 'rad5', text: '¿Cuál es el beneficio principal de la Técnica de Bramante sobre la de Clark?', options: ['Usa menos radiación', 'Permite identificar el cuadrante exacto de la raíz (MV, DV, MP, DP)', 'Es más rápida', 'No requiere 3 tomas'], correctAnswerIndex: 1, explanation: 'Utiliza un mapeo exacto por cuadrantes, indispensable para endodoncia de alta precisión.', type: 'multiple-choice' },
          { id: 'rad6', text: 'La técnica Interproximal (Aleta de Mordida) es la elección primaria para el diagnóstico de:', options: ['Lesiones apicales', 'Caries interproximales incipientes y altura de cresta ósea', 'Fracturas radiculares verticales', 'Dientes incluidos'], correctAnswerIndex: 1, explanation: 'Evalúa de forma idónea la cresta interalveolar y detección de caries interproximales.', type: 'multiple-choice' },
          { id: 'rad7', text: 'Radiográficamente, un Quiste Periapical se diferencia de un Granuloma principalmente por:', options: ['Estar asociado a un diente vital', 'Su tamaño (usualmente > 1 cm) y bordes corticalizados definidos', 'Presentar siempre dolor agudo', 'Ser una zona radiopaca'], correctAnswerIndex: 1, explanation: 'Los quistes son típicamente mayores de 1 cm y poseen un contorno radiopaco nítido.', type: 'multiple-choice' },
          { id: 'rad8', text: '¿Qué característica distingue a la Osteítis Condensante del Hueso Esclerótico?', options: ['El hueso esclerótico está fusionado al ápice', 'La Osteítis está fusionada al ápice y asociada a necrosis pulpar', 'La Osteítis no tiene origen inflamatorio', 'Son lo mismo'], correctAnswerIndex: 1, explanation: 'La Osteítis Condensante se asocia a origen inflamatorio y necrosis pulpar activa.', type: 'multiple-choice' },
          { id: 'rad9', text: 'La anomalía de forma consistente en la unión de dos o más dientes únicamente a través del cemento es:', options: ['Fusión', 'Geminación', 'Concrescencia', 'Dilaceración'], correctAnswerIndex: 2, explanation: 'La concrescencia es la unión de dos raíces dentarias únicamente por cemento.', type: 'multiple-choice' },
          { id: 'rad10', text: 'La técnica de Le Master se utiliza en molares superiores para:', options: ['Localizar el cuarto conducto', 'Evitar la superposición de la apófisis cigomática (malar)', 'Medir la longitud real', 'Evaluar el seno maxilar'], correctAnswerIndex: 1, explanation: 'Desplaza la sombra de la apófisis cigomática paralelizando la película con torundas.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-anestesia',
    title: '2. Anestesia y Anatomía Clínica',
    lessons: [
      {
        id: 'anes-1',
        title: 'Técnicas de Bloqueo',
        description: 'Puntos gatillo y seguridad anestésica.',
        icon: '💉',
        color: 'bg-blue-600',
        questions: [
          { id: 'an1', text: '¿Cuál es el límite posterior del espacio pterigomandibular?', options: ['Músculo Masetero', 'Glándula Parótida', 'Músculo Pterigoideo Medial', 'Rama Mandibular'], correctAnswerIndex: 1, explanation: 'La parótida limita este espacio; penetrarla puede provocar parálisis facial.', type: 'multiple-choice' },
          { id: 'an2', text: '¿Qué componente del anestésico local causa reacciones alérgicas tipo I?', options: ['Epinefrina', 'Cloruro de Sodio', 'Metilparabeno', 'Agua destilada'], correctAnswerIndex: 2, explanation: 'Los parabenos (conservantes) son los alérgenos responsables en cartuchos multidosis.', type: 'multiple-choice' },
          { id: 'an3', text: 'La técnica de Vazirani-Akinosi se indica cuando el paciente presenta:', options: ['Trismo severo', 'Infección en el área', 'Alergia a la lidocaína', 'Reflejo nauseoso'], correctAnswerIndex: 0, explanation: 'Es una técnica a boca cerrada perfecta para limitaciones graves de apertura.', type: 'multiple-choice' },
          { id: 'an4', text: 'Un paciente refiere parálisis transitoria de la mitad de la cara inmediatamente después de un bloqueo del nervio alveolar inferior. ¿A qué se debe?', options: ['Inyección accidental dentro de la parótida afectando ramas del VII facial', 'Inyección intravascular directa en la arteria alveolar inferior', 'Bloqueo reflejo del trigémino', 'Hematoma compresivo instantáneo'], correctAnswerIndex: 0, explanation: 'Introducir la aguja muy hacia atrás penetra la glándula parótida afectando el nervio facial.', type: 'multiple-choice' },
          { id: 'an5', text: '¿Cuál es el nervio anestesiado si depositamos solución en la fosa pterigopalatina para bloquear de manera completa un cuadrante superior?', options: ['Nervio Maxilar V2', 'Nervio Mandibular V3', 'Nervio Alveolar Superior Posterior', 'Nervio Infraorbitario'], correctAnswerIndex: 0, explanation: 'La fosa pterigopalatina contiene el tronco de V2, bloqueando toda la hemimaxila.', type: 'multiple-choice' },
          { id: 'an6', text: '¿Cuál es la principal ventaja anatómica y clínica de la técnica de Gow-Gates frente a Spix?', options: ['Bloquea V3 a nivel más alto en el cuello del cóndilo con menor riesgo de aspiración', 'No requiere anestesiar el nervio bucal', 'Es estrictamente a boca cerrada', 'Dura la mitad del tiempo clínico'], correctAnswerIndex: 0, explanation: 'Gow-Gates es un bloqueo troncular de V3 alto, logrando mayor tasa de éxito.', type: 'multiple-choice' },
          { id: 'an7', text: '¿Qué rama sensitiva del trigémino NO se anestesia con Spix y requiere refuerzo para exodoncia?', options: ['Nervio Bucal', 'Nervio Lingual', 'Nervio Mentoniano', 'Nervio Auriculotemporal'], correctAnswerIndex: 0, explanation: 'El nervio bucal (sensitivo oclusal) requiere refuerzo infiltrativo vestibular local.', type: 'multiple-choice' },
          { id: 'an8', text: '¿Qué vasoconstrictor está contraindicado en pacientes bajo antidepresivos tricíclicos por riesgo de crisis hipertensiva?', options: ['Levonordefrina', 'Epinefrina', 'Felipresina', 'Lidocaína simple'], correctAnswerIndex: 0, explanation: 'La levonordefrina y norepinefrina potencian su actividad presora con tricíclicos.', type: 'multiple-choice' }
        ]
      },
      {
        id: 'anes-anat',
        title: 'Osteología y Neuroanatomía',
        description: 'Estudio de los huesos del cráneo y forámenes.',
        icon: '💀',
        color: 'bg-slate-700',
        questions: [
          { id: 'anat-q1', text: 'Un paciente presenta una parálisis facial mímica tras un traumatismo en la región mastoidea. ¿Por qué orificio emerge el nervio afectado?', options: ['Conducto auditivo interno', 'Agujero estilomastoideo', 'Fisura petrotimpánica', 'Agujero rasgado posterior'], correctAnswerIndex: 1, explanation: 'El nervio facial (VII par) emerge del orificio estilomastoideo.', type: 'multiple-choice' },
          { id: 'anat-q2', text: 'Durante un análisis cefalométrico, el punto "Nasión" se localiza en:', options: ['En la glabela', 'En la espina nasal del frontal', 'En la intersección de la sutura frontonasal', 'En los arcos superciliares'], correctAnswerIndex: 2, explanation: 'Nasión es el cruce de la sutura internasal con la sutura frontonasal.', type: 'multiple-choice' },
          { id: 'anat-q3', text: 'Al realizar una elevación de seno maxilar, ¿a través de qué estructura del etmoides ocurre el drenaje natural al meato medio?', options: ['Lámina perpendicular', 'Infundíbulo etmoidal', 'Celdillas etmoidales posteriores', 'Crista galli'], correctAnswerIndex: 1, explanation: 'Drena al meato medio discurriendo por el infundíbulo etmoidal.', type: 'multiple-choice' },
          { id: 'anat-q4', text: 'Un paciente refiere pérdida del olfato tras traumatismo facial. ¿Qué estructura ósea se ha fracturado?', options: ['Lámina perpendicular', 'Cornete superior', 'Lámina cribosa del etmoides', 'Ala menor del esfenoides'], correctAnswerIndex: 2, explanation: 'La lámina cribosa da paso a los filetes del nervio olfatorio.', type: 'multiple-choice' },
          { id: 'anat-q5', text: '¿En qué zona del peñasco del temporal descansa el Ganglio de Gasser?', options: ['Cara posterosuperior del peñasco', 'Vértice de la apófisis mastoides', 'Cara anterosuperior (Cavum de Meckel)', 'Borde superior del peñasco'], correctAnswerIndex: 2, explanation: 'El ganglio trigeminal se aloja en la cara anterosuperior del peñasco.', type: 'multiple-choice' },
          { id: 'anat-q6', text: '¿Qué rama del trigémino sale por el agujero oval del esfenoides?', options: ['Nervio Oftálmico (V1)', 'Nervio Maxilar (V2)', 'Nervio Mandibular (V3)', 'Nervio Cuerda del Tímpano'], correctAnswerIndex: 2, explanation: 'El nervio mandibular (V3) egresa de la base craneal por el foramen oval.', type: 'multiple-choice' },
          { id: 'anat-q7', text: 'Durante exodoncia superior, se genera comunicación bucosinusal. ¿Qué estructura ósea modula la resonancia vocal?', options: ['La lámina perpendicular del etmoides', 'Los cornetes etmoidales', 'La apófisis crista galli', 'El agujero ciego'], correctAnswerIndex: 1, explanation: 'Los senos maxilares y cornetes actúan como cámaras de modulación vocal.', type: 'multiple-choice' },
          { id: 'anat-q8', text: '¿Cuál es el punto craneométrico de unión entre las suturas coronal y sagital?', options: ['Lambda', 'Pterión', 'Bregma', 'Asterión'], correctAnswerIndex: 2, explanation: 'Bregma marca la confluencia de ambas suturas en la bóveda craneal.', type: 'multiple-choice' },
          { id: 'anat-q9', text: 'El nervio hipogloso (XII) abandona el cráneo a través de un conducto situado en:', options: ['Las masas laterales del occipital', 'La porción basilar del occipital', 'La apófisis pterigoides', 'Peñasco del temporal'], correctAnswerIndex: 0, explanation: 'El conducto condíleo anterior atraviesa las masas laterales del occipital.', type: 'multiple-choice' },
          { id: 'anat-q10', text: 'El músculo pterigoideo externo se inserta primeramente en:', options: ['Ala menor del esfenoides', 'Cara externa de la lámina lateral de la apófisis pterigoides', 'Cara interna de la lámina medial de la apófisis pterigoides', 'Gancho de la pterigoides'], correctAnswerIndex: 1, explanation: 'Se inserta en la porción lateral de la lámina pterigoidea externa.', type: 'multiple-choice' }
        ]
      },
      {
        id: 'anes-cirugia',
        title: 'Cirugía Bucal y Bloqueo Regional',
        description: 'Principios quirúrgicos, elevadores, agujas y complicaciones vasculares.',
        icon: '🔪',
        color: 'bg-indigo-600',
        questions: [
          { id: 'anesq_1', text: 'Al planificar la exodoncia de un tercer molar inferior, ¿cuál es la técnica de anestesia troncular indicada para dicha región?', options: ['Infiltrativa supraperióstica', 'Bloqueo del nervio alveolar inferior', 'Intrapulpar directa anterior', 'Técnica extraoral infraorbitaria'], correctAnswerIndex: 1, explanation: 'La técnica troncular alveolar inferior insensibiliza toda la hemimandíbula del cuadrante.', type: 'multiple-choice' },
          { id: 'anesq_2', text: '¿Cuáles son las referencias anatómicas que determinan la punción de la técnica de Spix?', options: ['Agujero mentoniano y primer premolar superior', 'Borde posterior del paladar y fosa esfenoidal', 'Línea de oclusión del maxilar superior', 'Base de rama ascendente, línea oblicua interna y escotadura pterigomandibular'], correctAnswerIndex: 3, explanation: 'Usa estas marcas palpables y visibles para guiar el trayecto de la aguja.', type: 'multiple-choice' },
          { id: 'anesq_3', text: 'Al retirar la aguja durante la técnica del dentario inferior, ¿qué nervio sensitivo lingual se anestesia?', options: ['Nervio Oftálmico', 'Nervio Lingual', 'Nervio Cuerda del Tímpano', 'Nervio Miohioideo'], correctAnswerIndex: 1, explanation: 'Se retira un tercio de la aguja y se redirige para depositar solución en el nervio lingual.', type: 'multiple-choice' },
          { id: 'anesq_4', text: '¿Qué par craneal y rama inervan sensitivamente las piezas mandibulares y tejidos de soporte?', options: ['V par - Rama oftálmica', 'X par - Rama torácica', 'V par - Rama mandibular V3', 'VII par - Rama cervicofacial'], correctAnswerIndex: 2, explanation: 'El V3 es mixto; da sensibilidad dentaria y motricidad masticatoria.', type: 'multiple-choice' },
          { id: 'anesq_5', text: '¿Qué complicación transoperatoria aguda previene realizar una aspiración previa antes del vaciado anestésico?', options: ['Fractura de la aguja', 'Inyección intravascular accidental y toxicidad', 'Desgarro del pilar amigdalino', 'Pigmentación dentaria'], correctAnswerIndex: 1, explanation: 'Previene la inyección de la solución directo al torrente arterial o alveolar.', type: 'multiple-choice' },
          { id: 'anesq_6', text: '¿Qué aguja se indica para el bloqueo troncular alveolar inferior en adultos?', options: ['Extracorta 30G para niños', 'Larga 25G o 27G para evitar deflexión y asegurar profundidad', 'Curva de sutura de seda', 'De aspiración roma flexible'], correctAnswerIndex: 1, explanation: 'Permite alcanzar con precisión el espacio pterigomandibular profundo.', type: 'multiple-choice' },
          { id: 'anesq_7', text: 'Al presentarse una parálisis facial transitoria por técnica Spix, ¿cuál es el signo clínico ocular patonogmónico?', options: ['Nistagmo horizontal', 'Midriasis refleja', 'Lagrimeo de color amarillento', 'Incapacidad para cerrar el párpado ipsilateral (Signo de Bell)'], correctAnswerIndex: 3, explanation: 'La infiltración del VII par anula la motricidad del músculo orbicular del párpado.', type: 'multiple-choice' },
          { id: 'anesq_8', text: '¿Qué maniobra es prioritaria mientras persista la parálisis facial transitoria?', options: ['Indicar enjuagues calientes', 'Exodoncia inmediata', 'Disparar láser de baja intensidad', 'Colocar parche y lágrimas para prevenir resecamiento corneal'], correctAnswerIndex: 3, explanation: 'La incapacidad del parpadeo predispone a úlceras corneales graves por resecamiento.', type: 'multiple-choice' },
          { id: 'anesq_9', text: '¿Qué estructura ósea utiliza el nervio mentoniano para emerger del conducto interno?', options: ['Agujero mentoniano', 'Conducto incisivo', 'Canal palatino mayor', 'Agujero redondo superior'], correctAnswerIndex: 0, explanation: 'El agujero mentoniano da egreso a la rama mentoniana terminal del V3.', type: 'multiple-choice' },
          { id: 'anesq_10', text: '¿A qué nivel de raíces dentales promedio egresa el orificio mentoniano?', options: ['Ápice dental del canino inferior', 'Ápice del primer molar inferior', 'Fondo incisivo de centrales', 'Entre los ápices de los premolares inferiores'], correctAnswerIndex: 3, explanation: 'Comúnmente se localiza en la cortical externa entre ambos premolares.', type: 'multiple-choice' },
          { id: 'anesq_11', text: '¿Qué nombre recibe la prolongación anterior intraósea del nervio alveolar inferior?', options: ['Nervio incisivo', 'Nervio bucal', 'Nervio milohioideo', 'Nervio alveolar superior anterior'], correctAnswerIndex: 0, explanation: 'El nervio incisivo continúa el trayecto óseo hacia mesial para inervar canino e incisivos.', type: 'multiple-choice' },
          { id: 'anesq_12', text: '¿Cuál es el fin clínico inmediato de ejecutar una sindesmotomía antes de aplicar el elevador?', options: ['Fracturar la raíz apical', 'Lavar el alveolo', 'Eliminar tabla alveolar', 'Separar e incidir inserciones de encía marginal en el cuello dentario'], correctAnswerIndex: 3, explanation: 'Previene desgarros en encía e inserciones vestibulares/linguales en la tracción quirúrgica.', type: 'multiple-choice' },
          { id: 'anesq_13', text: '¿En qué principios mecánicos o físicos se basa el uso de elevadores rectos o de bota?', options: ['Palanca de cuarta clase', 'Tracción perpendicular de polea', 'Flexión elástica plástica', 'Principio de palanca, cuña y eje de rotación con apoyo óseo'], correctAnswerIndex: 3, explanation: 'Usa el hueso alveolar circundante como fulcro para luxar progresivamente el resto radicular.', type: 'multiple-choice' },
          { id: 'anesq_14', text: '¿Qué músculo forma el límite interno del espacio pterigomandibular?', options: ['Músculo masetero', 'Músculo temporal', 'Músculo pterigoideo interno (medial)', 'Músculo digástrico anterior'], correctAnswerIndex: 2, explanation: 'El pterigoideo interno delimita el espacio por la cara medial.', type: 'multiple-choice' },
          { id: 'anesq_15', text: '¿Qué ligamento se extiende desde la espina del esfenoides a la espina de Spix?', options: ['Ligamento esfenomandibular', 'Ligamento estilomandibular', 'Ligamento capsular de la ATM', 'Ligamento de la glándula parótida'], correctAnswerIndex: 0, explanation: 'El ligamento esfenomandibular brinda anclaje accesorio en la língula o espina de Spix.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-farma',
    title: '3. Farmacología y Seguridad',
    lessons: [
      {
        id: 'farma-1',
        title: 'Terapéutica Dental',
        description: 'Antibióticos, analgésicos e interacciones.',
        icon: '💊',
        color: 'bg-red-600',
        questions: [
          { id: 'f1', text: 'Dosis profiláctica de Amoxicilina para prevención de Endocarditis Bacteriana:', options: ['500 mg 1h antes', '1g 1h antes', '2g 1h antes', '2g 24h antes'], correctAnswerIndex: 2, explanation: 'Según la AHA, la dosis es de 2 gramos una hora antes del procedimiento.', type: 'multiple-choice' },
          { id: 'f2', text: 'Paciente hipertenso con Enalapril. ¿Qué AINE evitar por riesgo de daño renal?', options: ['Paracetamol', 'Ibuprofeno', 'Aspirina', 'Cualquier AINE de uso prolongado'], correctAnswerIndex: 3, explanation: 'La combinación IECA + AINE + Diurético es altamente nefrotóxica.', type: 'multiple-choice' },
          { id: 'f3', text: '¿Cuál es el mecanismo de acción primordial de los anestésicos locales del grupo de las amidas como la Lidocaína?', options: ['Bloqueo de canales de sodio dependientes de voltaje', 'Bloqueo de receptores adrenérgicos alfa', 'Activación de los receptores GABA', 'Inhibición de la bomba de protones'], correctAnswerIndex: 0, explanation: 'Se unen a receptores específicos en el canal de sodio, impidiendo la despolarización axonal.', type: 'multiple-choice' },
          { id: 'f4', text: '¿Cuál es la dosis máxima de epinefrina recomendada para ser utilizada de forma segura en un paciente cardiopático controlado?', options: ['0.04 mg', '0.2 mg', '1.0 mg', '0.4 mg'], correctAnswerIndex: 0, explanation: 'En pacientes con compromiso cardiopático, el límite es de 0.04 mg de epinefrina.', type: 'multiple-choice' },
          { id: 'f5', text: 'En caso de alergia tipo I (anafiláctica) a las penicilinas, ¿qué fármaco oral es el alternativo idóneo para profilaxis de endocarditis?', options: ['Clindamicina (600 mg)', 'Amoxicilina (1 g)', 'Cefalexina (2 g)', 'Metronidazol (500 mg)'], correctAnswerIndex: 0, explanation: 'En alérgicos graves a penicilinas se opta tradicionalmente por Clindamicina 600mg.', type: 'multiple-choice' },
          { id: 'f6', text: '¿Cuál de los siguientes analgésicos está catalogado como AINE selectivo de la enzima COX-2, reduciendo significativamente los efectos adversos gástricos?', options: ['Celecoxib', 'Ketorolaco', 'Ibuprofeno', 'Naproxeno'], correctAnswerIndex: 0, explanation: 'El Celecoxib inhibe específicamente la COX-2 sin alterar la barrera protectora de la COX-1 digestiva.', type: 'multiple-choice' },
          { id: 'f7', text: '¿Cuál es el efecto terapéutico secundario de la prescripción preoperatoria de Dexametasona de 4 a 8 mg antes de la cirugía de terceros molares?', options: ['Disminución del edema, trismo y dolor posoperatorios', 'Prevención de infecciones asociadas', 'Incremento del sangrado intraoperatorio', 'Ninguno, es solo analgésico'], correctAnswerIndex: 0, explanation: 'Los corticoides preoperatorios reducen notablemente el proceso inflamatorio agudo y el trismo.', type: 'multiple-choice' },
          { id: 'fq_1', text: 'Al prescribir Diclofenaco o Meloxicam, ¿cuál es el mecanismo molecular que reduce el dolor inflamatorio?', options: ['Activación de histamina', 'Excreción renal de potasio', 'Inhibición de la síntesis de prostaglandinas por bloqueo de COX-2', 'Estimulación del flujo salivar parasimpático'], correctAnswerIndex: 2, explanation: 'Los analgésicos AINEs inhiben la enzima ciclooxigenasa (COX) disminuyendo la síntesis del mediador de prostaglandinas.', type: 'multiple-choice' },
          { id: 'fq_2', text: '¿Qué preparado comercial dental se denomina "Otosporin"?', options: ['Cemento definitivo libre de resina', 'Revelador bicolor plaquee', 'Agente silano de acople cerámico', 'Medicamento intracanal que asocia antibióticos con corticoides'], correctAnswerIndex: 3, explanation: 'Asocia hidrocortisona, neomicina y polimixina B para uso de desinfección temporaria en conductos.', type: 'multiple-choice' },
          { id: 'fq_3', text: '¿Cuál es la función clínica de un desinfectante intracanal medicado colocado entre sesiones en endodoncia?', options: ['Remineralizar raíces', 'Ensanchar de forma pasiva conductos', 'Adherir gutaperchas residuales', 'Reducir la carga bacteriana intra-conducto y disminuir sintomatología aguda periapical'], correctAnswerIndex: 3, explanation: 'Tiene acción bacteriostática/bactericida contra cepas endodónticas y aplaca el dolor perirradicular.', type: 'multiple-choice' },
          { id: 'fq_4', text: 'Fármaco antibiótico de elección inicial para un proceso infeccioso periapical agudo en pacientes no alérgicos:', options: ['Eritromicina', 'Ciprofloxacina', 'Espectinomicina', 'Amoxicilina sola o combinada con Ácido Clavulánico'], correctAnswerIndex: 3, explanation: 'Los betalactámicos son la elección primaria debido a su excelente biodisponibilidad y espectro ante microbios orales comunes.', type: 'multiple-choice' },
          { id: 'fq_5', text: '¿Qué efecto digestivo nocivo se asocia al uso prolongado e irracional de un AINE clásico?', options: ['Lichen plano maligno', 'Ageusia reversible de la lengua', 'Caries radiculares masivas', 'Irritación de mucosa gástrica, gastritis o riesgo de ulceración péptica'], correctAnswerIndex: 3, explanation: 'Inhiben la prostaglandina gástrica COX-1 protectora de la mucosa estomacal.', type: 'multiple-choice' },
          { id: 'fq_6', text: '¿Qué acción produce un vasoconstrictor adrenérgico integrado en el cartucho de anestesia?', options: ['Alcaliniza el compuesto anestésico', 'Acelera la absorción en el torrente general', 'Disminuye la duración terapéutica', 'Produce vasoconstricción local, prolongando el efecto y controlando el sangrado local'], correctAnswerIndex: 3, explanation: 'Limita la irrigación capilar en la zona, reteniendo más tiempo el fármaco en los troncos de fibras axónicas.', type: 'multiple-choice' },
          { id: 'fq_7', text: '¿Cuál es el principal órgano de metabolización de los anestésicos amidas (ej. Lidocaína)?', options: ['El riñón por glomérulo', 'El bazo periférico', 'El pulmón por aire respirado', 'El hígado por el sistema de enzimas microsomales hepáticas'], correctAnswerIndex: 3, explanation: 'El hígado posee las amidasas y citocromos necesarios para desdoblar las cadenas del tipo amida.', type: 'multiple-choice' },
          { id: 'fq_8', text: '¿Qué enzima plasmática destruye la cadena de los anestésicos locales del grupo Éster?', options: ['Lipasa pancreática', 'Glucosa reductasa', 'Amilasa salival activa', 'Pseudocolinesterasa plasmática (butirilcolinesterasa)'], correctAnswerIndex: 3, explanation: 'Los ésteres sufren hidrólisis veloz en el plasma por acción de la pseudocolinesterasa.', type: 'multiple-choice' },
          { id: 'fq_9', text: '¿Por qué decrece la capacidad del anestésico en un tejido inflamado con pH ácido?', options: ['Se acelera la excreción', 'Las bacterias destruyen la aguja', 'Se colapsa el epineuro', 'La acidez bucal favorece la molécula ionizada hidrofílica, imposibilitando atravesar la vaina lipídica del axón'], correctAnswerIndex: 3, explanation: 'Al bajar el pH, predomina la porción salina ionizada (con carga), que es incapaz de pasar la bicapa lipídica del axón.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-materiales',
    title: '4. Biomateriales',
    lessons: [
      {
        id: 'mat-1',
        title: 'Propiedades y Mezclas',
        description: 'Alginatos, siliconas y resinas.',
        icon: '🏗️',
        color: 'bg-amber-500',
        questions: [
          { id: 'm1', text: '¿Qué tipo de reacción de fraguado tiene el Alginato?', options: ['Física', 'Química irreversible (Gelación)', 'Polimerización', 'Evaporación'], correctAnswerIndex: 1, explanation: 'Es una reacción química entre el alginato de potasio y el sulfato de calcio.', type: 'multiple-choice' },
          { id: 'm2', text: 'Subproducto de la silicona por condensación que causa contracción:', options: ['Agua', 'Alcohol etílico', 'Hidrógeno', 'Oxígeno'], correctAnswerIndex: 1, explanation: 'La liberación de alcohol causa la inestabilidad dimensional característica.', type: 'multiple-choice' },
          { id: 'm3', text: 'El yeso alfa-hemidrato modificado (Yeso Tipo IV o piedra de alta resistencia) se prefiere para dados de trabajo principalmente por:', options: ['Su excelente dureza superficial y mínima expansión de fraguado (menor a 0.10%)', 'Ser el más económico de mezclar', 'Fraguado instantáneo en 3 minutos', 'No necesitar dosificación'], correctAnswerIndex: 0, explanation: 'El yeso tipo IV ofrece la rigidez y estabilidad dimensional micrométrica idóneas para coronas y puentes.', type: 'multiple-choice' },
          { id: 'm4', text: '¿Qué cemento odontológico destaca por interactuar y adherirse químicamente por sí mismo a los iones calcio e hidroxiapatita del diente?', options: ['Ionómero de vidrio', 'Fosfato de zinc', 'Cemento de resina simple', 'Óxido de zinc eugenol'], correctAnswerIndex: 0, explanation: 'El ionómero de vidrio contiene ácido poliacrílico que genera enlaces iónicos químicos con el calcio de la dentina y el esmalte.', type: 'multiple-choice' },
          { id: 'm5', text: '¿Cuál es la función del silano comercial en el protocolo restaurador con resinas dentales?', options: ['Actuar como agente de acoplamiento químico entre la matriz orgánica resinosas y el relleno inorgánico de sílice', 'Acelerar el fraguado', 'Servir de ácido grabador', 'Desensibilizar la dentina expuesta'], correctAnswerIndex: 0, explanation: 'El silano posee grupos funcionales que enlazan la porción inorgánica con el polímero, mejorando drásticamente las propiedades de tensión.', type: 'multiple-choice' },
          { id: 'm6', text: 'La silicona por adición se diferencia de la de condensación en odontopediatría y prótesis fija porque:', options: ['No libera subproductos volátiles, otorgándole una estabilidad dimensional sobresaliente', 'Genera alcohol etílico como desecho', 'Es soluble al agua corriente', 'Posee menor elasticidad residual'], correctAnswerIndex: 0, explanation: 'Las siliconas por adición polimerizan sin formar subproductos residuales dañinos, permitiendo vaciar modelos días después.', type: 'multiple-choice' },
          { id: 'm7', text: '¿Qué fenómeno físico perjudicial acompaña invariablemente a la luz halógena o LED durante el fotocurado de las resinas compuestas?', options: ['Contracción de polimerización', 'Expansión higroscópica tardía', 'Inhibición química total', 'Disolución ácida de resina'], correctAnswerIndex: 0, explanation: 'La conversión de monómeros a polímeros crea una reducción volumétrica llamada contracción de polimerización, induciendo potencial microfiltración.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-operatoria',
    title: '5. Operatoria Dental',
    lessons: [
      {
        id: 'op-1',
        title: 'Clínica Restauradora',
        description: 'Caries y protocolos de adhesión.',
        icon: '🦷',
        color: 'bg-green-600',
        questions: [
          { id: 'o1', text: 'Según ICDAS, una microcavidad con ruptura del esmalte es código:', options: ['1', '2', '3', '4'], correctAnswerIndex: 2, explanation: 'ICDAS 3 es ruptura localizada del esmalte sin dentina visible.', type: 'multiple-choice' },
          { id: 'o2', text: 'Función del "Primer" en un sistema adhesivo:', options: ['Grabar esmalte', 'Hacer la dentina hidrofóbica', 'Sellar túbulos', 'Limpiar barro dentinario'], correctAnswerIndex: 1, explanation: 'Prepara la colágena hidrofílica para recibir la resina hidrofóbica.', type: 'multiple-choice' },
          { id: 'o3', text: '¿Qué representa el "Factor C" o factor de configuración cavitaria y por qué una clase I oclusal tiene el peor factor?', options: ['La relación de paredes unidas vs libres; una clase I tiene un Factor C de 5 lo que produce máximo estrés por tracción', 'El tiempo de vida útil de la lámpara', 'El grado de acidez del grabado total', 'El porcentaje inorgánico del material restaurador'], correctAnswerIndex: 0, explanation: 'El Factor C es el cociente de áreas unidas al diente entre áreas libres. Al tener 5 paredes unidas y solo 1 libre (oclusal), el estrés de contracción no puede disiparse.', type: 'multiple-choice' },
          { id: 'o4', text: '¿Qué concentración típica de ácido fosfórico se aplica de forma estandarizada sobre el diente para acondicionar esmalte y dentina?', options: ['35% - 37%', '10% - 15%', '50%', '5%'], correctAnswerIndex: 0, explanation: 'El ácido fosfórico al 35%-37% crea microporosidades de retención reticular en el esmalte y abre los túbulos dentinarios de forma segura.', type: 'multiple-choice' },
          { id: 'o5', text: '¿Cuál es el propósito central del grabado ácido sobre la dentina en un sistema adhesivo convencional de grabado total de 2 o 3 pasos?', options: ['Desmineralizar la capa superficial y exponer la red colágena para lograr infiltración híbrida', 'Sellar de forma instantánea el tejido pulpar', 'Desinfectar virus cariogénicos', 'Remineralizar con cristales de oxalatos'], correctAnswerIndex: 0, explanation: 'El grabado disuelve la hidroxiapatita superficial, dejando expuesto el andamiaje colágeno donde se infiltrarán los monómeros para formar la capa híbrida.', type: 'multiple-choice' },
          { id: 'o6', text: '¿Cuál es la ventaja de utilizar la técnica de sándwich abierta con ionómero de vidrio de alta densidad cubierto por resina?', options: ['Ofrece sellado cervical hermético auto-adhesivo, liberación de flúor y biocompatibilidad en márgenes subgingivales', 'Es más estética que colocar resina sola', 'Disminuye la retención mecánica de la corona', 'No requiere uso posterior de lámpara LED'], correctAnswerIndex: 0, explanation: 'El ionómero tiene autoadhesión física y química en dentina profunda donde la contracción de la resina podría generar brechas.', type: 'multiple-choice' },
          { id: 'o7', text: 'Durante el fotoactivado de una resina compuesta por bloques (Bulk-Fill) convencionales, ¿cuál es el espesor máximo seguro sugerido por capa?', options: ['Hasta 4.0 - 5.0 mm según fabricante', '0.5 mm', '10.0 mm', 'Únicamente 1.5 mm'], correctAnswerIndex: 0, explanation: 'Las resinas tipo Bulk-Fill poseen fotosensibilizadores avanzados que facilitan la polimerización profunda de incrementos más gruesos de hasta 4 o 5 mm.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-casos',
    title: '6. Casos Clínicos Transversales',
    lessons: [
      {
        id: 'casos-final',
        title: 'Simulacro de Examen de Grado',
        description: 'Casos integrados de alta complejidad y de razonamiento crítico.',
        icon: '🎓',
        color: 'bg-black',
        questions: [
          { id: 'c1', text: 'Paciente hipertenso requiere exodoncia de 3.8. En la RX se observa lesión distal compatible con "joroba" del Dr. Cotrina. ¿Diagnóstico y precaución?', options: ['Quiste Dentígero - No usar anestesia', 'Quiste Paradentario - Controlar PA y usar vasoconstrictor con cautela', 'Odontoma - Antibiótico profiláctico', 'Ameloblastoma - Exodoncia inmediata'], correctAnswerIndex: 1, explanation: 'Combina Radiología del doctor Cotrina (Quiste Paradentario o joroba) y Farmacología de control hipertensivo.', type: 'multiple-choice' },
          { id: 'c2', text: 'Durante una endodoncia, localiza una perforación en el cuadrante Disto-Vestibular mediante 3 tomas. ¿Qué técnica utilizó?', options: ['Clark', 'Paralelismo', 'Bramante', 'Le Master'], correctAnswerIndex: 2, explanation: 'Bramante es indispensable para ubicar con precisión conductos o variaciones anatómicas por cuadrantes.', type: 'multiple-choice' },
          { id: 'c3', text: 'Paciente con riesgo de Endocarditis requiere tallado para corona. Sufre trismo por inyección previa. ¿Conducta?', options: ['2g Amoxicilina + Técnica de Akinosi', '500mg Amoxicilina + Técnica de Spix', 'No medicar + Técnica de Clark', '1g Amoxicilina + Técnica de infiltración'], correctAnswerIndex: 0, explanation: 'Asocia Profilaxis antibiótica sistémica para endocarditis y Técnica de Akinosi para trismo.', type: 'multiple-choice' },
          { id: 'c4', text: 'RX muestra imagen radiolúcida > 1cm en ápice de 2.1 no vital, con borde corticalizado. ¿Tratamiento inicial?', options: ['Exodoncia', 'Conducto + Seguimiento radiográfico', 'Antibiótico solo', 'Curetaje inmediato'], correctAnswerIndex: 1, explanation: 'Un quiste radicular se trata de inicio mediante terapia endodóntica y control de evolución ósea posterior.', type: 'multiple-choice' },
          { id: 'c5', text: 'Paciente con dolor en 4.6. RX muestra masa opaca fusionada al ápice y necrosis pulpar. ¿Qué es?', options: ['Hueso Esclerótico', 'Osteítis Condensante', 'Odontoma', 'Cementoblastoma'], correctAnswerIndex: 1, explanation: 'La osteítis condensante cursa unida al plano periapical como reacción reactiva ante una necrosis de canal.', type: 'multiple-choice' },
          { id: 'c6', text: 'Se sospecha de conducto palatino extra. Al mover el cono a distal, el conducto se mueve a mesial. ¿Dónde está?', options: ['Palatino', 'Vestibular', 'Mesial', 'Lingual'], correctAnswerIndex: 1, explanation: 'Regla MLOV: Movimiento opuesto al cono significa localización por vestibular.', type: 'multiple-choice' },
          { id: 'c7', text: 'Paciente alérgico a la Penicilina requiere cirugía. ¿Alternativa profiláctica?', options: ['Eritromicina', 'Clindamicina 600mg', 'Amoxicilina 2g', 'Ibuprofeno 800mg'], correctAnswerIndex: 1, explanation: 'En alérgicos severos tipo 1, la clindamicina oral representa el sustituto profiláctico estandarizado.', type: 'multiple-choice' },
          { id: 'c8', text: 'En una RX de molares superiores, la sombra del malar impide ver los ápices. ¿Qué técnica aplica?', options: ['Bite-wing', 'Le Master', 'Clark', 'Akinosi'], correctAnswerIndex: 1, explanation: 'Le Master separa la apófisis cigomática paralelizando el eje fílmico.', type: 'multiple-choice' },
          { id: 'c9', text: 'RX muestra pieza 1.3 incluida y un "halo radiolúcido" rodeando su corona. ¿Diagnóstico probable?', options: ['Quiste Dentígero', 'Quiste Periapical', 'Granuloma', 'Osteítis'], correctAnswerIndex: 0, explanation: 'Afección asociada a corona retenida del canino superior es típicamente un quiste folicular o dentígero.', type: 'multiple-choice' },
          { id: 'c10', text: 'Paciente hipertenso de grado controlado asiste a consulta con Aspirina. Registra un dolor en 3.5 con esmalte quebrado clase II. ¿Riesgo principal con procedimientos quirúrgicos invasivos complejos?', options: ['Fallo renal de shock', 'Hemorragia post-operatoria por baja agregación', 'Reacción anafiláctica tipo I', 'No hay alteración ni riesgo alguno'], correctAnswerIndex: 1, explanation: 'La aspirina es antiagregante plaquetario e incrementa las fases de sangrado perjudicial.', type: 'multiple-choice' },
          { id: 'c11', text: 'Paciente embarazada en segundo trimestre y diabética estable presenta pulpitis irreversible sintomática con percusión positiva en 3.6. ¿Qué anestesia y analgésicos utilizará para un tratamiento de conducto seguro?', options: ['Anestesia general intubada y Ketorolaco intramuscular', 'Lidocaína con epinefrina baja o Mepivacaína simple + Tratamiento endodóntico de urgencia + Paracetamol', 'No anestesiar y dar Aspirina cada 6 horas', 'Bloqueo supraperióstico e Ibuprofeno 800mg profiláctico'], correctAnswerIndex: 1, explanation: 'La lidocaína en dosis controladas es segura en el segundo trimestre. El paracetamol es el analgésico más estudiado y seguro del embarazo.', type: 'multiple-choice' },
          { id: 'c12', text: 'Paciente con Enalapril asiste con trismo grave (15 mm apertura) por infección molar mandibular. ¿Qué técnica anestésica se utiliza y qué AINE prolongado evitar por interacción?', options: ['Técnica Spix - Evitar paracetamol por interacción hepática', 'Técnica Vazirani-Akinosi a boca cerrada - Evitar AINEs prolongados ya que bloquean prostaglandinas renales aminorando el efecto antihipertensivo', 'Técnica Gow-Gates alta - Evitar metamizol por dolor', 'Infiltración vestibular - Evitar aspirina por necrosis renal'], correctAnswerIndex: 1, explanation: 'Akinosi es la vía de elección en trismo severo. Los AINEs prolongados reducen la eficacia de los IECA debido a interferencia de vasodilatación renal.', type: 'multiple-choice' },
          { id: 'c13', text: 'Paciente de prótesis totales nuevas manifiesta dolores de ATM, cansancio muscular masetero, dientes que chocan al hablar y DVR - DVO de cero milímetros. ¿Cuál es la alteración física biomecánica presente?', options: ['Baja del flujo de saliva sublingual', 'Estomatitis papilar por mala preparación de acrílico', 'Dimensión Vertical de Oclusión (DVO) aumentada en exceso con consecuente anulación del espacio libre fisiológico interoclusal', 'Reabsorción del hueso cortical alveolar inferior'], correctAnswerIndex: 2, explanation: 'Debe preservarse siempre el espacio libre basal de 2 a 4 milímetros entre rodetes para evitar fatiga neuromuscular constante.', type: 'multiple-choice' },
          { id: 'c14', text: 'Inmediatamente después de una inyección troncular Spix sin contactar pared ósea medial, el paciente es incapaz de cerrar el párpado ipsilateral (Signo de Bell). ¿Qué error de abordaje explica esta complicación transitoria?', options: ['Compromiso alérgico del nervio oftálmico', 'Hematoma retroorbitario instantáneo', 'Introducción de aguja muy posterior penetrando el estroma de la glándula parótida y bloqueando ramas del motor nervio facial VII', 'Inyección intravasal dentro del nervio alveolar inferior'], correctAnswerIndex: 2, explanation: 'Pasar la aguja muy atrás deposita el líquido en el espesor parotídeo donde emerge e inerva motoramente el nervio facial.', type: 'multiple-choice' },
          { id: 'c15', text: 'Para endodoncia de 1.2 se toma una RX inclinando el cono hacia disto-vestibular. El conducto extra se ve desplazado significativamente hacia mesial del plano principal. Según MLOV de Clark, ¿dónde está localizado?', options: ['Localización por cara palatina', 'Exactamente alineado en mesio-distal', 'Localización por cara vestibular', 'Indica posición interlingual profunda'], correctAnswerIndex: 2, explanation: 'Regla Clark: Movimiento opuesto al cono (cono distal, conducto corre a mesial) indica posición vestibular.', type: 'multiple-choice' },
          { id: 'c16', text: 'Adolescente diabético con HbA1c de 10.5% acude con bolsas periodontales severas e higiene baja. ¿Qué conducta de rehabilitación periodontal quirúrgica de inserción es viable?', options: ['Gingivectomía el mismo día', 'Posponer cirugía invasiva electiva o periodonto-quirúrgica, priorizar raspado conservador no invasivo y derivar de urgencia para control metabólico de glucosa', 'Proceder a injertos de hueso amplios', 'No tiene riesgo quirúrgico, prescribir diclofenaco de continuo'], correctAnswerIndex: 1, explanation: 'Valores HbA1c > 7% reflejan baja compensación inmune y defectos de cicatrización, contraindicando técnicas invasivas electivas.', type: 'multiple-choice' },
          { id: 'c17', text: 'Paciente presenta dolor agudo oclusal post-clínico en molar restaurado clase I profunda con resina Bulk-Fill fotocurada en monobloque gordo de 6 mm. ¿Qué factores técnicos desencadenaron el dolor?', options: ['Uso de un cemento sellador de fosfato', 'Exceso en espesor de bloque Bulk-Fill (límite seguro 4-5 mm) y una cavidad con alto Factor C de 5 que concentró severo estrés por tracción', 'Grabado con ácido silano en toda la dentina', 'Hipersensibilidad idiopática por biotipo'], correctAnswerIndex: 1, explanation: 'Un Factor C de 5 (cavidad oclusal cerrada) más un sobreespesor del bloque deja monómero libre y tracciona mecánicamente las paredes pulpares.', type: 'multiple-choice' },
          { id: 'c18', text: 'Pieza anterior no vital sensible a percusión vertical y con fístula vestibular requiere limpieza endodóntica. ¿Qué protocolo es el estándar de oro?', options: ['Únicamente suero salino y obturación el mismo día', 'Hipoclorito de Sodio (disolvente y antimicrobiano) + EDTA al 17% (remoción del smear layer inorgánico) + Pasta intracanal (ej. medicada con Otosporin e Hidróxido de calcio)', 'Ácido fosfórico como irrigador principal + Gutapercha sin cemento', 'Clorhexidina densa y momificación con formocresol continuo'], correctAnswerIndex: 1, explanation: 'Garantiza la eliminación combinada del tejido orgánico pulpar y la capa inorgánica generada en el limado dentinario.', type: 'multiple-choice' },
          { id: 'c19', text: 'Se planifica exodoncia baja mediante una técnica de Gow-Gates para anestesiar de forma completa el nervio mandibular izquierdo. ¿Qué marcas anatómicas visuales guían la inclinación de la aguja carpule?', options: ['Línea oblicua mandibular externa', 'Comisura labial contralateral, el trago auricular del lado ipsilateral y la cúspide distovestibular del segundo molar superior', 'El rafe pterigopalatino y el borde palatino de caninos', 'Fondo de surco labial anterior'], correctAnswerIndex: 1, explanation: 'Son los reparos extraorales e intraorales validados para aproximar la aguja hacia el espacio externo del cóndilo mandibular.', type: 'multiple-choice' },
          { id: 'c20', text: 'Se interroga al alumno sobre los componentes del medicamento intracanal "Otosporin". ¿Cuál es su composición química activa?', options: ['Eugenol puro e hidróxido de sodio denso', 'Polimixina B con Neomicina (cobertura antibacteriana amplia) e Hidrocortisona (corticoide antiinflamatorio)', 'Silano de acoplamiento de matriz', 'Formoldehído de momificación radicular'], correctAnswerIndex: 1, explanation: 'Asocia antibióticos tópicos selectivos con un corticoide potente para calmar la sensibilidad periodontal post-extirpación.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-endoperio',
    title: '7. Endodoncia, Periodoncia y Ortodoncia',
    lessons: [
      {
        id: 'endoperio-1',
        title: 'Diagnóstico Pulpar y Tejidos de Soporte',
        description: 'Patologías pulpares, periapicales y clasificación periodontal.',
        icon: '🔬',
        color: 'bg-cyan-700',
        questions: [
          { id: 'ep1', text: 'Un ya citado paciente presenta dolor agudo espontáneo que aumenta drásticamente al acostarse y persiste tras retirar el frío. ¿Diagnóstico pulpar?', options: ['Pulpitis reversible', 'Pulpitis irreversible sintomática', 'Necrosis pulpar completa', 'Periodontitis apical sintomática con fístula'], correctAnswerIndex: 1, explanation: 'La permanencia prolongada del dolor agudo ante el frío es patonogmónico de pulpitis irreversible.', type: 'multiple-choice' },
          { id: 'ep2', text: '¿Qué irrigante de elección disuelve el tejido orgánico y tiene excelente poder antimicrobiano?', options: ['Clorhexidina al 2%', 'Hipoclorito de sodio (NaOCl) al 1% - 5.25%', 'EDTA al 17%', 'Suero fisiológico'], correctAnswerIndex: 1, explanation: 'El Hipoclorito de sodio es el único irrigante que disuelve selectivamente la pulpa necrótica.', type: 'multiple-choice' },
          { id: 'ep3', text: '¿Cuál es la función clínica fundamental del agente quelante EDTA al 17%?', options: ['Disolver la materia orgánica pulpar residual', 'Eliminar la porción inorgánica del barro dentinario (smear layer)', 'Anestesiar localmente las fibras del conducto', 'Lubricar únicamente el acceso radicular'], correctAnswerIndex: 1, explanation: 'El EDTA quelata el ión calcio removiendo mecánicamente el barro inorgánico post-instrumental.', type: 'multiple-choice' },
          { id: 'ep4', text: 'Según las directrices de la AAP (2017) para enfermedades periodontales, ¿qué factor categoriza el "Estadío" clínico?', options: ['La velocidad estimada de avance del defecto óseo', 'La severidad, complejidad de manejo clínico y pérdida de inserción interdental clínica', 'El nivel de placa bacteriana detectada en superficies', 'El hábito personal de tabaco del paciente'], correctAnswerIndex: 1, explanation: 'El Estadío representa severidad y complejidad destructiva, mientras que el Grado calcula la rapidez evolutiva.', type: 'multiple-choice' },
          { id: 'ep5', text: '¿Cuál es la medida en milímetros de la anchura biológica coronal promedio?', options: ['0.5 mm', '2.04 mm', '4.0 mm', '1.0 mm'], correctAnswerIndex: 1, explanation: 'Suma de inserción conjuntiva y epitelio de unión que promedia 2.04 milímetros.', type: 'multiple-choice' },
          { id: 'ep6', text: '¿Qué tipo de morfología en un defecto óseo periodontal tiene la prognosis más favorable para regeneración ósea guiada?', options: ['Defecto óseo supra-alveolar', 'Defecto infraóseo de 3 paredes', 'Defecto infraóseo de 1 pared', 'Defecto de furca clase III en molares inferiores'], correctAnswerIndex: 1, explanation: 'Las tres paredes preservan la estabilidad y nutrición vascular óptima para el injerto óseo.', type: 'multiple-choice' },
          { id: 'ep7', text: '¿Cuál es el bacilo anaerobio estricto perteneciente al "complejo rojo" de Socransky, íntimamente asociado a bolsas periodontales activas y persistentes?', options: ['Aggregatibacter actinomycetemcomitans', 'Porphyromonas gingivalis', 'Streptococcus mutans', 'Actinomyces viscosus'], correctAnswerIndex: 1, explanation: 'Porphyromonas gingivalis codifica factores que destruyen proteolíticamente el soporte de colágeno alveolar.', type: 'multiple-choice' },
          { id: 'ep8', text: '¿Cuál es la patología de una pieza dental muerta (insensible a estímulos térmicos) con agudo dolor punzante ante la palpación vertical y percusión?', options: ['Pulpitis reversible incipiente', 'Necrosis pulpar con compromiso inflamatorio propagado al ligamento periodontal apical', 'Hipersensibilidad de esmalte cervical', 'Traumatismo oclusal agudo sin patología previa'], correctAnswerIndex: 1, explanation: 'La necrosis causa muerte nerviosa de sensibilidad, mientras que la expansión bacteriana al periodonto apical causa respuesta propioceptiva dolorosa al tacto.', type: 'multiple-choice' }
        ]
      },
      {
        id: 'endoperio-2',
        title: 'Ortodoncia, Ortopedia y Fisiología Pulpar',
        description: 'Cefalometría, maloclusiones y transmisión neurológica del dolor.',
        icon: '📐',
        color: 'bg-sky-600',
        questions: [
          { id: 'ortq_1', text: '¿Cuál es la utilidad clínica principal de la radiografía cefálica lateral (cefalometría)?', options: ['Medir la presencia de bacterias radiculares', 'Medir el volumen de saliva sublingual', 'Calcular desgaste proximal de cúspides', 'Evaluar las relaciones esqueléticas, dentoalveolares y de tejidos de perfil sagital'], correctAnswerIndex: 3, explanation: 'Permite trazar ángulos y líneas craneométricas para evaluar el biotipo esquelético.', type: 'multiple-choice' },
          { id: 'ortq_2', text: '¿Qué anomalías oclusales se evalúan con precisión en el trazado de perfil lateral?', options: ['Grado de caries proximales', 'Nivel de colágeno alveolar', 'Calcificación de conductos sutiles', 'Anomalías esqueléticas de clase II o clase III, patrones de crecimiento y asimetrías sagitales'], correctAnswerIndex: 3, explanation: 'Se realiza diagnóstico esquelético maxilomandibular en sentido sagital anteroposterior.', type: 'multiple-choice' },
          { id: 'ortq_3', text: '¿Cuál es la separación funcional entre la ortopedia dentofacial de la ortodoncia?', options: ['Fuerzas electromagnéticas versus brackets', 'Brackets metálicos anteriores versus elásticos', 'Uso en tercera edad versus bebés sin dientes', 'La ortopedia modifica y guía el crecimiento óseo, mientras la ortodoncia mueve piezas dentarias sobre el alveolo'], correctAnswerIndex: 3, explanation: 'La ortopedia es esquelética y funcional en pacientes con potencial de crecimiento; ortodoncia es movimiento dentario.', type: 'multiple-choice' },
          { id: 'ortq_4', text: '¿En qué principios dentales basó Angle la clasificación de las maloclusiones?', options: ['Cúspides del canino superior', 'Cúspide de premolares inferiores', 'Distancia de úvula a lengua', 'Relación de la cúspide mesiovestibular del primer molar superior con el surco mesiovestibular del primer molar inferior'], correctAnswerIndex: 3, explanation: 'Consideraba al primer molar superior como punto fijo e inmutable en el arco dentario.', type: 'multiple-choice' },
          { id: 'ortq_5', text: '¿Qué estructura ósea y función tienen las trompas de Eustaquio?', options: ['Conductos salivales que drenan boca', 'Válvulas de control yugular', 'Prolongación que ancla al masetero', 'Conductos que comunican la nasofaringe con el oído medio, equilibrando las presiones de aire del tímpano'], correctAnswerIndex: 3, explanation: 'Canaliza presiones aéreas entre el oído medio y las cavidades aéreas nasofaríngeas.', type: 'multiple-choice' },
          { id: 'ortq_6', text: '¿Qué representa anatómica y funcionalmente el Plexo de Rashkow pulpar?', options: ['Vasos del paladar que nutren saliva', 'Glándulas mucosas de amígdalas', 'Conjunto elástico periarticular de ATM', 'Un plexo nervioso situado en la zona subodontoblástica responsable de la transmisión dolorosa e hidrodinámica pulpar'], correctAnswerIndex: 3, explanation: 'Plexo nervioso de fibras mielínicas A-delta profundas por debajo del odontoblasto dentinario.', type: 'multiple-choice' },
          { id: 'ortq_7', text: '¿Qué punto cefalométrico representa la espina nasal anterior y el punto Gonion?', options: ['Puntos blandos de inserción labial', 'Zonas exclusivas de molares deciduas', 'Anclajes tendinosos del cuello', 'Punto esquelético óseo anterior del maxilar y el ángulo de inserción muscular mandibular'], correctAnswerIndex: 3, explanation: 'Representan accidentes y reparos esqueléticos indispensables para estudios cefalométricos.', type: 'multiple-choice' },
          { id: 'ortq_8', text: '¿Qué puntos de la línea media facial corresponden a glabela y trichum?', options: ['Mentón óseo y cartílago nasal', 'Agujero ciego y apófisis coronoides', 'Puntos oclusales de caninos', 'Glabela es el punto más prominente entre las cejas; Trichum marca la línea de inicio del cabello en la frente'], correctAnswerIndex: 3, explanation: 'Reparos estéticos del perfil facial para evaluar asimetrías verticales y proporciones del rostro.', type: 'multiple-choice' },
          { id: 'ortq_9', text: '¿A qué estructura mandibular corresponde el punto óseo cefalométrico "Pogonion" (Pg)?', options: ['Zona cóncava de la rama ascendente posterior', 'Escotadura articular sigmoidea', 'Agujero interno de entrada mandibular', 'Al punto más prominente y anterior de la sínfisis mentoniana del mentón'], correctAnswerIndex: 3, explanation: 'Es el punto de máxima proyección ósea anterior en el mentón mandibular.', type: 'multiple-choice' },
          { id: 'ortq_10', text: '¿Qué respuesta sintomática es la normal en pruebas de vitalidad pulpar térmica con frío?', options: ['Anestesia permanente', 'Fuerte dolor pulsátil constante de horas', 'Necrosis o cambio a color gris dental', 'Respuesta dolorosa inmediata provocada que se disipa inmediatamente tras retirar el frío'], correctAnswerIndex: 3, explanation: 'Refleja que los filetes nerviosos y la irrigación pulpar normal de la cámara pulpar conducen la sensibilidad sin inflamación irreversible.', type: 'multiple-choice' },
          { id: 'ortq_11', text: '¿Qué plano traza el trayecto cefalométrico desde Porion al punto Orbitario?', options: ['Plano de Camper posterior', 'Plano Silla-Nasion esquelético', 'Plano mandibular gnatográfico', 'Plano de Frankfurt horizontal'], correctAnswerIndex: 3, explanation: 'Determina la horizontal de Frankfurt indispensable para orientar la posición natural de la cabeza.', type: 'multiple-choice' },
          { id: 'ortq_12', text: 'Punto cefalométrico que marca el centro de la silla turca del esfenoides:', options: ['Punto Nasion (N)', 'Punto Porion (Po)', 'Punto Basion (Ba)', 'Punto Silla (S)'], correctAnswerIndex: 3, explanation: 'Punto esquelético de referencia craneal media profunda localizado en la fosa hipofisiaria.', type: 'multiple-choice' },
          { id: 'ortq_13', text: 'Punto que representa la unión de la sutura frontonasal:', options: ['Punto Orbitario (Or)', 'Punto Pogonion (Pg)', 'Punto Gnation (Gn)', 'Punto Nasion (N)'], correctAnswerIndex: 3, explanation: 'Cruza sagitalmente el plano sagital medio y sutura ósea nasal.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-diagnostico',
    title: '8. Diagnóstico y Semiología',
    lessons: [
      {
        id: 'diagnostico-1',
        title: 'Historia Clínica y Exploración',
        description: 'Anamnesis, percusión, signos vitales y consentimiento informado.',
        icon: '📋',
        color: 'bg-teal-600',
        questions: [
          { id: 'diagq_1', text: '¿Qué alteración estructural indica principalmente un resultado positivo a la percusión vertical?', options: ['Compromiso del ligamento periodontal apical o periapical', 'Pérdida ósea cortical sistémica', 'Fractura leve coronaria de esmalte', 'Retracción gingival idiopática'], correctAnswerIndex: 0, explanation: 'La fuerza de percusión vertical se transmite axialmente al soporte apical y del ligamento periodontal superior posterior.', type: 'multiple-choice' },
          { id: 'diagq_2', text: 'Durante la semiología oral, ¿qué condición o compromiso clínico suele indicar la percusión horizontal?', options: ['Necrosis pulpar estricta sin infección', 'Compromiso o lesión del ligamento periodontal en sus paredes laterales', 'Calcificación distrófica biliar', 'Fístula pura gingival'], correctAnswerIndex: 1, explanation: 'La percusión horizontal evalúa el periodonto de inserción lateral y trauma oclusal complementario.', type: 'multiple-choice' },
          { id: 'diagq_3', text: '¿Cuál es el rango normal para la presión arterial sistólica y diastólica en un paciente adulto basal?', options: ['140/90 mm Hg', '100/60 mm Hg', '130/85 mm Hg', '120/80 mm Hg'], correctAnswerIndex: 3, explanation: 'Representa la presión óptima basal aprobada internacionalmente.', type: 'multiple-choice' },
          { id: 'diagq_4', text: '¿A qué cuadro corresponde la cefalea por elevación de presión arterial?', options: ['Hipotensión severa', 'Crisis hipoglucémica aguda', 'Shock neurogénico central', 'Hipertensión arterial'], correctAnswerIndex: 3, explanation: 'La resistencia vascular alta y vasoconstricción periférica cursa con dolores de cabeza.', type: 'multiple-choice' },
          { id: 'diagq_5', text: '¿Qué cuadro presenta un paciente con presión disminuida, mareos y síncopes recurrentes?', options: ['Hipertensión arterial', 'Cetoacidosis diabética', 'Infarto agudo de miocardio', 'Hipotensión arterial'], correctAnswerIndex: 3, explanation: 'La hipotensión arterial disminuye transitoriamente la perfusión de oxígeno al plano encefálico.', type: 'multiple-choice' },
          { id: 'diagq_6', text: '¿Cuál es el propósito legal del consentimiento informado en odontología?', options: ['Registro de costos contables', 'Evolución diaria unilateral', 'Folleto clínico comercial', 'Un documento real donde el paciente autoriza formalmente el tratamiento, respaldando legalmente al profesional'], correctAnswerIndex: 3, explanation: 'Es un convenio explícito indispensable de validación y límites terapéuticos pactados.', type: 'multiple-choice' },
          { id: 'diagq_7', text: '¿Qué requisitos otorgan validez clínica y legal plena al consentimiento informado?', options: ['Llenado exclusivo por familiares', 'Firma única del director del centro regional', 'Traducción obligatoria a lengua extranjera', 'Llenado completo con datos del paciente, del odontólogo, tratamiento detallado, riesgos y firmas de ambos'], correctAnswerIndex: 3, explanation: 'Requiere la firma física del paciente tras haber comprendido el alcance, riesgos y costos del acto clínico.', type: 'multiple-choice' },
          { id: 'diagq_8', text: 'Paciente sin dolor requiere retratamiento de conducto visible en valoración general. ¿Qué paso es indispensable?', options: ['Exodoncia rápida el mismo día', 'Apertura inmediata sin imágenes', 'Terapia profiláctica por 15 días', 'Indicar y ejecutar de manera obligatoria un examen diagnóstico complementario (radiografía)'], correctAnswerIndex: 3, explanation: 'Para evaluar anatomía radicular, obturación o la presencia de lesiones periapicales no visibles externamente.', type: 'multiple-choice' },
          { id: 'diagq_9', text: '¿Qué maniobra se indica para obtener la dimensión vertical en reposo (DVR)?', options: ['Deglución forzada sin labios húmedos', 'Mordida en fuerza máxima oclusal', 'Insertar bloques de madera oclusales', 'Métodos fonéticos (pronunciar "M") y de relajación muscular para ubicar mandíbula en posición postural'], correctAnswerIndex: 3, explanation: 'Lleva la mandíbula al espacio de inactividad de los músculos maseteros y temporales.', type: 'multiple-choice' },
          { id: 'diagq_10', text: '¿Qué biotipo facial se asocia a una dimensión vertical del tercio inferior aumentada?', options: ['Biotipo Braquifacial', 'Biotipo Mesofacial normodivergente', 'Biotipo Euriprósopo puro', 'Biotipo Dolicofacial'], correctAnswerIndex: 3, explanation: 'Presenta patrón hiperdivergente de mordida abierta con sínfisis y distancia ósea más amplias.', type: 'multiple-choice' },
          { id: 'diagq_11', text: '¿Qué patología se caracteriza por el desgaste e involuntario rechinamiento de los dientes?', options: ['Síndrome de Sjogren secundario', 'Parálisis de Bell lateral', 'Neuralgia del trigémino mandibular', 'Bruxismo'], correctAnswerIndex: 3, explanation: 'El bruxismo nocturno o diurno es descontrolado neuromuscular que acarrea severos daños del esmalte dentario.', type: 'multiple-choice' },
          { id: 'diagq_12', text: '¿Cuál es la meta clínica de cuantificar la movilidad dentaria periodontal?', options: ['Determinar tono restaurador', 'Hacer cálculos para volumen anestésico', 'Medir calibre del esmalte gingival', 'Medir el nivel de pérdida de soporte alveolar e inflamación del ligamento de inserción periodontal'], correctAnswerIndex: 3, explanation: 'Ayuda a diagnosticar la gravedad de la patología periodontal activa.', type: 'multiple-choice' },
          { id: 'diagq_13', text: '¿Qué material local determina desgastes e interferencias en oclusión de dientes?', options: ['Sondas periodontales milimetradas', 'Matrices en acero seccional premoldeados', 'Hilos dentales encerados densos', 'Papel de articular o hilos de marcar contactos oclusales'], correctAnswerIndex: 3, explanation: 'Indica los contactos selectivos prematuros sobre las crestas oclusales de resina o metal.', type: 'multiple-choice' },
          { id: 'diagq_14', text: 'Paciente refiere dolor agudo localizado solo al masticar en molar cubierto por corona protésica fija. ¿Sospecha diagnóstica?', options: ['Pulpitis transitoria térmica estacional', 'Amelogénesis de tipo hipoplásico', 'Quiste palatino de azar asintomático', 'Fractura radicular por debajo del margen protésico o impactación de alimento interdental'], correctAnswerIndex: 3, explanation: 'Dolores axiales locales ante cargas masticatorias orientan a agrietamientos radiculares por fatiga.', type: 'multiple-choice' },
          { id: 'diagq_15', text: 'Examen de excelencia para valorar molares retenidos próximos al conducto dentario en 3D:', options: ['Radiografía oclusal o incisiva', 'Radiografía bisectriz de mordida', 'Fotografía clínica periauricular', 'Tomografía computarizada de haz cónico (CBCT)'], correctAnswerIndex: 3, explanation: 'Evita superposiciones de imagen del conducto, ofreciendo cortes tridimensionales.', type: 'multiple-choice' },
          { id: 'diagq_16', text: '¿Cuál es el primer apartado a recopilar en la anamnesis o entrevista del paciente?', options: ['Plan de tratamiento quirúrgico', 'Presupuesto de prótesis fijas', 'Gasto de materiales biológicos', 'Datos de filiación o identificación del paciente'], correctAnswerIndex: 3, explanation: 'Abre el historial legal que identifica al propietario del documento clínico.', type: 'multiple-choice' },
          { id: 'diagq_17', text: '¿Qué define la causa inicial por la que un paciente acude al odontólogo?', options: ['Anamnesis hereditaria', 'Evolución final pos-operatoria', 'Plan preventivo de caries', 'Motivo de consulta'], correctAnswerIndex: 3, explanation: 'Es la síntesis del problema principal en palabras del paciente.', type: 'multiple-choice' },
          { id: 'diagq_18', text: '¿Qué proceso subyace ante una fístula de drenaje activa en la encía vestibular?', options: ['Hiperemia traumática del esmalte', 'Hiperplasia mucosa idiopática', 'Retención de terceros molares sanos', 'Drenaje espontáneo de exudado purulento de una infección ósea alveolar de origen periapical o periodontal crónico'], correctAnswerIndex: 3, explanation: 'La acumulación purulenta erosiona la cortical ósea externa abriendo una vía espontánea de salida.', type: 'multiple-choice' },
          { id: 'diagq_19', text: 'Maniobra útil para evaluar consistencia de un aumento de volumen gingival blando:', options: ['Transiluminación halógena', 'Percusión vertical oclusal', 'Raspado con limas periodontales', 'Palpación manual o bidigital local de la zona comprometida'], correctAnswerIndex: 3, explanation: 'Permite clasificar si la masa es fluctuante (líquida), fibrosa (densa) o dura (ósea).', type: 'multiple-choice' },
          { id: 'diagq_20', text: '¿Cuál es el color gingival normal de una encía sana y su aspecto macroscópico?', options: ['Rojo brillante descamado', 'Blanco translúcido fibroso lineal', 'Gris opaco uniforme', 'Rosa pálido o coral con aspecto de "piel de naranja"'], correctAnswerIndex: 3, explanation: 'Refleja queratinización, excelente irrigación sanguínea y fijaciones conjuntivas con el periostio.', type: 'multiple-choice' },
          { id: 'diagq_21', text: 'Presión de 135/85 mm Hg por nerviosismo del paciente en sillón dental se clasifica como:', options: ['Crisis hiperglucémica extrema', 'Hipotensión grave transitoria', 'Normotensión idónea basal', 'Presión arterial elevada o prehipertensión leve inducida por ansiedad dental'], correctAnswerIndex: 3, explanation: 'La elevación por estrés transitorio de consulta (síndrome de bata blanca).', type: 'multiple-choice' },
          { id: 'diagq_22', text: 'Fibra pulpar responsable de conducir dolor agudo, punzante de instauración veloz ante el frío:', options: ['Fibras C amielínicas finas', 'Fibras simpáticas motoras', 'Fibras colágenas del estroma dentinario', 'Fibras A-delta mielínicas de conducción rápida'], correctAnswerIndex: 3, explanation: 'Las fibras A-delta son mielínicas de conducción rápida en el límite pulpa-dentina.', type: 'multiple-choice' },
          { id: 'diagq_23', text: 'Dolor sordo, pulsátil continuo mal localizado se asocia a qué fibra pulpar primaria?', options: ['Fibras A-beta motrices', 'Fibras colágenas gingivales', 'Fibras de la vaina de Hertwig', 'Fibras C amielínicas profundas'], correctAnswerIndex: 3, explanation: 'Las fibras C son amielínicas profundas y de velocidad de conducción baja.', type: 'multiple-choice' },
          { id: 'diagq_24', text: '¿Cuál es la limitación central de una radiografía periapical 2D ante pérdidas óseas incipientes por vestibular?', options: ['Incapacidad para ver esmalte coronal', 'Modifica dureza de la pulpa', 'Produce calor o dolor térmico mandibular', 'Superpone el espesor ósea cortical traduciendo estructuras 3D en sólo planos bidimensionales'], correctAnswerIndex: 3, explanation: 'Su naturaleza proyectiva 2D oculta reabsorciones iniciales en cortical vestibular o lingual.', type: 'multiple-choice' },
          { id: 'diagq_25', text: 'Signo audible seco y único al abrir o cerrar la mandíbula:', options: ['Soplido vascular carotídeo', 'Crepitación articular difusa o roce de lija', 'Frémito de inserción coronaria', 'Clic o chasquido articular de traslación condilar'], correctAnswerIndex: 3, explanation: 'Asociado a desplazamiento y recaptura del disco articular sobre el cóndilo.', type: 'multiple-choice' },
          { id: 'diagq_26', text: 'La crepitación articular auditiva (tipo rascado) se asocia principalmente a:', options: ['Subluxación condilar bilateral', 'Hipertrofia de masetero masivo', 'Infección salivar activa', 'Cambios degenerativos de superficies óseas de ATM (artrosis o reabsorción cortical condilar)'], correctAnswerIndex: 3, explanation: 'Consecuencia directa de erosiones de las superficies corticalizadas de contacto condíleo.', type: 'multiple-choice' },
          { id: 'diagq_27', text: 'Método diagnóstico ideal por imágenes para valorar con nitidez tejidos blandos y disco de ATM:', options: ['Tomografía lineal panorámica', 'Ortopantomografía digital', 'Cefalometría lateral de cráneo', 'Resonancia Magnética Nuclear (RMN)'], correctAnswerIndex: 3, explanation: 'Ofrece el contraste óptimo sin radiaciones ionizantes para estructuras blandas y disco de inserción.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-odontopediatria',
    title: '9. Odontopediatría y Pacientes Especiales',
    lessons: [
      {
        id: 'pacientes-med',
        title: 'Manejo en Pacientes Especiales y Embarazo',
        description: 'Manejo clínico seguro de pacientes gestantes, diabéticos y de riesgo sistémico.',
        icon: '🤱',
        color: 'bg-rose-600',
        questions: [
          { id: 'pedq_1', text: '¿Por qué conocer con certeza el periodo de gestación antes del manejo operatorio?', options: ['Determina el color de la corona dental', 'Permite obligar dieta líquida', 'Ayuda a planificar tratamientos meramente cosméticos', 'Garantiza evaluar la seguridad de tratamientos, fármacos y anestésicos locales impidiendo daños teratogénicos o distress del feto'], correctAnswerIndex: 3, explanation: 'Existen medicamentos y fármacos que atraviesan la barrera placentaria alterando el desarrollo fetal.', type: 'multiple-choice' },
          { id: 'pedq_2', text: '¿Trimestre de gestación catalogado como el más seguro para intervenciones dentales de rutina?', options: ['Primer trimestre', 'Tercer trimestre avanzado', 'Últimas semanas antes de parto', 'Segundo trimestre del embarazo'], correctAnswerIndex: 3, explanation: 'La organogénesis está completa y el volumen del útero no causa severo disconfort físico supino.', type: 'multiple-choice' },
          { id: 'pedq_3', text: 'Afección gingival inflamatoria común por cambios vasculares hormonales endógenos en el embarazo:', options: ['Necrosis ósea instantánea', 'Hiperplasia del esmalte coronario', 'Atrofia salivar parotídea irreversible', 'Gingivitis gestacional con marcada tendencia hemorrágica local'], correctAnswerIndex: 3, explanation: 'La progesterona exacerba la inflamación capilar ante bajas cantidades de biofilm.', type: 'multiple-choice' },
          { id: 'pedq_4', text: 'Mito clásico sobre pérdida de densidad dental en gestantes carente de rigor científico:', options: ['Aumento de dureza alveolar molares', 'Remisión espontánea de lesiones ICDAS 5', 'Disolución del cemento radicular', 'La afirmación de que el bebé "le roba el calcio de los dientes" debilitando el esmalte de la madre'], correctAnswerIndex: 3, explanation: 'El calcio del esmalte está fijo; deficiencias en dieta solo causan movilización de reservas óseas sistémicas.', type: 'multiple-choice' },
          { id: 'pedq_5', text: 'Patología de metabolismo caracterizada por niveles persistentemente altos de glucosa:', options: ['Insuficiencia mitral', 'Enfermedad de Addison', 'Cirrosis hepática', 'Diabetes mellitus'], correctAnswerIndex: 3, explanation: 'Afección que compromete la homeostasis inmune, vascular y de reparación epitelial.', type: 'multiple-choice' },
          { id: 'pedq_6', text: 'Inconveniente oral común en diabéticos descompensados que usan prótesis completas nuevas:', options: ['Tinción de acrílicos en tonos de glucosa', 'Hiperplasia condilar alveolar', 'Reabsorción acelerada de coronas nativas', 'Xerostomía (boca seca) y un severo retardo en cicatrización de micro-heridas gingivales'], correctAnswerIndex: 3, explanation: 'La hipofunción de saliva compromete el arrastre de detritos e impide la veloz reparación por microangiopatías.', type: 'multiple-choice' },
          { id: 'pedq_7', text: 'Consecuencia directa de una xerostomía crónica de soporte en un desdentado total:', options: ['Mejora adherencia de acrilatos', 'Elimina microorganismos de Candida', 'Atrofia el músculo temporal', 'Merma la succión salival de retención física de la prótesis superior y predispone a úlceras dolorosas por fricción'], correctAnswerIndex: 3, explanation: 'La saliva actúa como amortiguador mucoso y su película líquida es esencial para formar el vacío físico de postdamming.', type: 'multiple-choice' },
          { id: 'pedq_8', text: 'Sillón dental en 3er trimestre gestación se inclina hacia qué lado para evadir síndrome de hipotensión supina?', options: ['Totalmente plano hacia la derecha', 'Trendelenburg con cabeza baja', 'Boca abajo decúbito prono', 'Posición semisentada o con leve inclinación (y cuña) hacia el lado izquierdo de la paciente'], correctAnswerIndex: 3, explanation: 'Desplaza el peso del útero grávido de la vena cava inferior previniendo caída brusca del retorno cardíaco.', type: 'multiple-choice' },
          { id: 'pedq_9', text: '¿Por qué se evitan AINEs (ej. Ibuprofeno, Naproxeno) durante el tercer trimestre de embarazo?', options: ['Fomentan calcificaciones del esmalte fetal', 'Disuelven resinas de grabado', 'Producen xerostomía gingival', 'Por inducir riesgo fetal agudo de cierre prematuro del conducto arterioso fetal'], correctAnswerIndex: 3, explanation: 'Inhiben las prostaglandinas responsables de mantener permeable el conducto arterioso en la circulación fetal avanzada.', type: 'multiple-choice' },
          { id: 'pedq_10', text: 'Fármaco analgésico primario de amplio rango de bioseguridad aprobado en la gestación:', options: ['Aspirina de continuo', 'Ketorolaco ampollas', 'Indometacina supositorios', 'Paracetamol (Acetaminofén)'], correctAnswerIndex: 3, explanation: 'Carece de efectos hemodinámicos sobre conducto arterioso fetal en dosis terapéuticas estándar.', type: 'multiple-choice' },
          { id: 'pedq_11', text: 'Riesgo biológico de amoxicilina en embarazo según clasificación FDA:', options: ['Categoría A', 'Categoría C', 'Categoría X', 'Categoría B (Estudios en animales no muestran riesgo, sin hallazgos controlados en gestantes)'], correctAnswerIndex: 3, explanation: 'Es un fármaco betalactámico tradicionalmente catalogado de máxima bioseguridad clínica contra abscesos maternales.', type: 'multiple-choice' },
          { id: 'pedq_12', text: 'Shock súbito en paciente diabético insulinodependiente sometido a prolongado estrés en ayuno:', options: ['Cetoacidosis metabólica severa', 'Diabetes insípida neurogénica', 'Uremia renal aguda', 'Hipoglucemia aguda (shock insulínico por caída drástica de azúcar)'], correctAnswerIndex: 3, explanation: 'El consumo tisular por cortisol alto desploma el nivel de glucosa ante carencia de ingesta alimenticia previa.', type: 'multiple-choice' },
          { id: 'pedq_13', text: '¿Qué indicios alertan de una hipoglucemia inminente en el sillón clínico?', options: ['Piel caliente roja y sequedad parotídea', 'Somnolencia sin alteración motora', 'Mayor agudeza visual y ánimo feliz', 'Sudoración fría profusa, temblor muscular, taquicardia acelerada y estado confuso'], correctAnswerIndex: 3, explanation: 'Cascada autonómica de estimulación simpática ante la deprivación severa de nutrientes cerebrales.', type: 'multiple-choice' },
          { id: 'pedq_14', text: 'Manejo prioritario ante hipoglucemia leve en paciente diabético consciente:', options: ['Inyectar insulina subcutánea regular', 'Paro respiratorio inmediato', 'Respirar en bolsa de plástico', 'Suministrar vía oral bebidas azucaradas, jugos o carbohidratos de asimilación rápida'], correctAnswerIndex: 3, explanation: 'Reconstituye en minutos la glucemia celular revirtiendo la crisis de deprivación.', type: 'multiple-choice' },
          { id: 'pedq_15', text: 'Prueba de laboratorio estandarizada que calcula promedio de glucosa de últimos 3 meses:', options: ['Tira reactiva capilar de un solo día', 'Prueba de tolerancia oral', 'Densidad de urea en orina', 'Hemoglobina Glicosilada (HbA1c)'], correctAnswerIndex: 3, explanation: 'Mide la fracción porcentual de hemoglobina unida de forma estable e irreversible a moléculas de glucosa.', type: 'multiple-choice' },
          { id: 'pedq_16', text: 'Porcentaje de HbA1c idóneo indicador de un excelente control metabólico:', options: ['Superior a 12%', 'Fijo en rango de 9.5%', 'Acorde a peso del paciente', 'Por debajo del 7%'], correctAnswerIndex: 3, explanation: 'Refleja un rango glicémico controlado disminuyendo tasas de infecciones y fallas de cicatrización posoperatoria.', type: 'multiple-choice' },
          { id: 'pedq_17', text: '¿Por qué la diabetes de baja compensación tiene mayor resorción periodontal ósea?', options: ['Carecen de fibras de esmalte interalveolar', 'La glucosa liofiliza ligamentos gingivales', 'Cepillado con cerdas duras continuas', 'Por disfunción leucocitaria de neutrófilos, respuesta inmune deficiente e hiper-producción de interleucinas proinflamatorias locales'], correctAnswerIndex: 3, explanation: 'La hiperglicemia crónica glicosila proteínas matriciales, alterando la fagocitosis de patógenos.', type: 'multiple-choice' },
          { id: 'pedq_18', text: 'Hormonas de excreción endógena que aumentan congestión periodontal en embarazo:', options: ['Adrenalina arterial media', 'TSH tiroidea baja', 'Prostaglandina pélvica de parto', 'Marcada elevación de estrógenos y progesterona sistémicos'], correctAnswerIndex: 3, explanation: 'Favorecen dilatación venosa y proliferación capilar (microangio-hiperplasia gingival).', type: 'multiple-choice' },
          { id: 'pedq_19', text: 'Tumoración periodontal hiperplásica benigna de tejido hipervascularizada típica de gestantes:', options: ['Ameloblastoma maduro unilateral', 'Odontoma compuesto anterior', 'Fibroma gigante osificante profundo', 'Granuloma piógeno (Épulis del embarazo)'], correctAnswerIndex: 3, explanation: 'Respuesta gingival reparadora proliferativa exuberante ante trauma menor u biofilm en gestantes.', type: 'multiple-choice' },
          { id: 'pedq_20', text: 'Tratamiento indicado para Épulis del embarazo que no limita masticación ni estética severa:', options: ['Biopsia excisional cruenta precoz', 'Radioterapia por rayos gamma baja', 'Nitrato de plata diario al 50%', 'Excelente higiene guiada de biofilm dental y observar regresión natural pos-parto'], correctAnswerIndex: 3, explanation: 'La gran mayoría reduce drásticamente su volumen al estabilizarse el balance hormonal del posparto.', type: 'multiple-choice' }
        ]
      }
    ]
  },
  {
    id: 'mod-rehabilitacion',
    title: '10. Rehabilitación Oral y Prótesis',
    lessons: [
      {
        id: 'prostodoncia-tot',
        title: 'Prótesis Total y Parcial Fija',
        description: 'Sellado periférico, dimensiones oclusales, rodetes, zirconio y reabsorción residual.',
        icon: '🦷',
        color: 'bg-emerald-700',
        questions: [
          { id: 'rehq_1', text: 'Zonas de sobreextensión acrílica en flancos de prótesis total nueva generan:', options: ['Aumento de saliva conducto Stenon', 'Erupción acelerada antagonistas', 'Calcificación maseterina', 'Lesiones ulcerativas y heridas de fricción en la mucosa vestibular'], correctAnswerIndex: 3, explanation: 'El borde protésico excede los límites biológicos comprimiendo e hiriendo la inserción mucosa móvil.', type: 'multiple-choice' },
          { id: 'rehq_2', text: 'Objetivo de un idóneo sellado de la zona palatina posterior (postdamming):', options: ['Mejorar el color de resinas', 'Dar paso a fibra alimenticia posterior', 'Evitar que el usuario retire la base', 'Asegurar retención y estabilidad al formar una presión física negativa controlada (viento o vacío)'], correctAnswerIndex: 3, explanation: 'Previene la entrada de aire y líquidos desestabilizadores bajo el límite protésico posterior.', type: 'multiple-choice' },
          { id: 'rehq_3', text: 'Conducta idónea frente a la inserción inicial clínica de una prótesis completa:', options: ['Hervir la base durante dos horas', 'Dar indicación de uso ininterrumpido sin retiro por 30 días', 'Aplicar una película gruesa de cemento fosfato definitivo', 'Ejecutar controles clínicos minuciosos de oclusión y aliviar los puntos internos de presión mucolíticos detectados con gel indicador'], correctAnswerIndex: 3, explanation: 'Evita y soluciona prematuramente agresiones micro-traumáticas compresivas.', type: 'multiple-choice' },
          { id: 'rehq_4', text: 'Limitación clásica de coronas en zirconio puro monolítico antiguo:', options: ['Excesiva flexibilidad oclusal', 'Solubilidad bajo pH salivar', 'Falta de radiopacidad en exámenes', 'Elevada rigidez opaca inicial y susceptibilidad a astillamiento (chipping) de la porcelana de recubrimiento marginal'], correctAnswerIndex: 3, explanation: 'La interface cerámica-metal o cerámica-zirconio de cobertura puede sufrir delaminación o desprendimiento bajo cargas duras.', type: 'multiple-choice' },
          { id: 'rehq_5', text: 'Parámetros antes de realizar un incremento rehabilitador de Dimensión Vertical:', options: ['Volumen de folículos amigdalinos', 'Longitud de movilidad de la úvula', 'Distribución de glándulas sudoríparas', 'Análisis clínico de la Articulación Temporomandibular (ATM) y estado funcional de músculos masticadores'], correctAnswerIndex: 3, explanation: 'Un rango vertical alterado impacta severamente la sinergia muscular y salud intraarticular.', type: 'multiple-choice' },
          { id: 'rehq_6', text: '¿Qué es Dimensión Vertical de Oclusión (DVO) estructural?', options: ['Distancia de reposo postural mandibular', 'Ancho goníaco inferior transversal', 'Profundidad de la curva oclusal de Spee', 'Altura de tercio inferior al coincidir contactos oclusales de rodetes o piezas dentarias artificiales superiores e inferiores'], correctAnswerIndex: 3, explanation: 'La medida de perfil en oclusión céntrica o de contacto interdentario.', type: 'multiple-choice' },
          { id: 'rehq_7', text: 'Efecto de rehabilitar la DVO a un nivel excesivamente disminuido:', options: ['Rejuvenecimiento de mentón', 'Anula movimientos protrusivos', 'Merma del espacio libre interoclusal', 'Colapso de perfil del tercio inferior facial con mentón aproximado a la nariz y propensión a queilitis angular comisural'], correctAnswerIndex: 3, explanation: 'El sobrecierre mandibular proyecta la comisura labial, acumulando humedad de saliva que ulcera el ángulo oral.', type: 'multiple-choice' },
          { id: 'rehq_8', text: 'Efecto de sobreelevar la DVO aumentada sobrepasando márgenes biológicos:', options: ['Excesivo espacio libre masticatorio', 'Hipo-producción salivar parotídea', 'Aposición masiva de hueso alveolar', 'Fatiga muscular dolorosa, dolores de ATM por estiramiento de fibras, dificultad fonética y golpeteo masticatorio dental continuado'], correctAnswerIndex: 3, explanation: 'Elimina el espacio libre, manteniendo en constante contracción y asincronía la vía neuromuscular masticatoria.', type: 'multiple-choice' },
          { id: 'rehq_9', text: 'Material idóneo y estándar para elaborar bases de prótesis completas:', options: ['Cromo-cobalto fundido', 'Cerámicas de disilicato colado', 'Micro-resinas compuestas directas', 'Resina acrílica de termopolimerización (polimetilmetacrilato)'], correctAnswerIndex: 3, explanation: 'Ofrece excelente balance de biocompatibilidad, resistencia biológica de frotado y estabilidad tridimensional.', type: 'multiple-choice' },
          { id: 'rehq_10', text: 'Cambio óseo alveolar irreversible gradual posterior a exodoncias generalizadas:', options: ['Aposición ósea subperióstica', 'Pérdida por compactamiento medular', 'Hipertrofia de corticales del cuerpo', 'Reabsorción residual crónica de los rebordes alveolares del maxilar'], correctAnswerIndex: 3, explanation: 'Es un cambio fisiopatológico centrípeto en maxilar superior y centrífugo en mandíbula ante carencia de estímulo periodontal.', type: 'multiple-choice' },
          { id: 'rehq_11', text: 'Altura promedio recomendada anterior del rodete oclusal en maxilar superior del fondo de surco:', options: ['Entre 10 y 12 milímetros', 'Entre 30 y 35 milímetros', 'Menos de 5 milímetros', 'Entre 20 y 22 milímetros'], correctAnswerIndex: 3, explanation: 'Rango estético promedio indispensable para proyectar un adecuado soporte labial anterior.', type: 'multiple-choice' },
          { id: 'rehq_12', text: 'Línea de perfil facial que debe ser paralela al segmento anterior del rodete superior en el plano de Fox:', options: ['Plano lateral de Frankfurt', 'Línea oclusal del canino', 'Plano esquelético de sínfisis', 'Línea bipupilar transversal'], correctAnswerIndex: 3, explanation: 'Asegura la horizontalidad estética respecto al plano ocular del paciente.', type: 'multiple-choice' },
          { id: 'rehq_13', text: 'Plano de referencia externo para paralelizar sectores posteriores del rodete oclusal superior:', options: ['Plano interglabelar facial', 'Sutura fronto-parietal sagital', 'Línea perpendicular de la nariz', 'Línea de Camper (que corre desde el trago de la oreja al ala de la nariz en lateral)'], correctAnswerIndex: 3, explanation: 'Se asocia con el paralelismo del plano oclusal biológico de los molares.', type: 'multiple-choice' },
          { id: 'rehq_14', text: 'Diferencia métrica de altura de perfil de reposo DVR y de contacto DVO:', options: ['Área de inoclusión lingual', 'Área de compresión palatina posterior', 'Ángulo mandibular superior', 'Espacio libre interoclusal o de inoclusión fisiológica'], correctAnswerIndex: 3, explanation: 'Espacio libre en el cual los arcos no ocluyen ni chocan, permitiendo la relajación muscular funcional.', type: 'multiple-choice' },
          { id: 'rehq_15', text: 'Párametro normal en milímetros del espacio libre interoclusal en equilibrio:', options: ['De 5 a 8 milímetros fijos', 'Cero milímetros estricto', 'Superior a los 10 milímetros', 'Entre 2 y 4 milímetros'], correctAnswerIndex: 3, explanation: 'Valor estándar indispensable para que se disipe el estrés de contacto interdentario.', type: 'multiple-choice' },
          { id: 'rehq_16', text: 'Fuerzas de retención física de prótesis completas superiores por saliva en paladar:', options: ['Atornillado mucoso celular', 'Uso obligado de adhesivos químicos', 'Rugosidad mecánica alveolar', 'Mecanismos de adhesión, cohesión, presión atmosférica y tensión superficial de la delgada película de fluido salivar'], correctAnswerIndex: 3, explanation: 'La conjunción física hidrodinámica genera resistencia de vacío contra el desalojo.', type: 'multiple-choice' },
          { id: 'rehq_17', text: 'Punto posterior de límite de adaptación para una prótesis total inferior:', options: ['Agujero palatino posterior', 'Trígono incisivo lateral inferior', 'Apófisis estiloides temporal', 'Papila piriforme o almohadilla retromolar'], correctAnswerIndex: 3, explanation: 'Estructura fibrosa invariable que delimita el fondo de soporte mandibular distomolar.', type: 'multiple-choice' },
          { id: 'rehq_18', text: '¿Por qué la base protésica inferior debe cubrir totalmente la almohadilla retromolar?', options: ['Fomenta erupción de cordales', 'Ayuda de freno para el paso vocal', 'Favorece coloración rosada encías', 'Brinda soporte, estabilidad y excelente sellado periférico en el cuadrante inferior'], correctAnswerIndex: 3, explanation: 'La papila es un elemento fibroso denso que previene reabsorciones rápidas disminuyendo presiones de soporte.', type: 'multiple-choice' },
          { id: 'rehq_19', text: 'Afección del paladar blando por adaptaciones deficientes, falta de higiene y proliferación de Candida albicans:', options: ['Pénfigo de mucosa oral', 'Liquen reticulado lineal', 'Leucoplasia vellosa lateral', 'Estomatitis subprotésica (hiperplasia papilar de encías posterior)'], correctAnswerIndex: 3, explanation: 'La oclusión hermética sin higiene acumula células descamativas y micosis fúngicas.', type: 'multiple-choice' }
        ]
      }
    ]
  }
];
